---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.type }}
      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
